import vchart from '../src/index.js'
import $ from 'jquery'

var el = document.querySelector('#root');
var data = [];
var option = {
/*	colors:['blue',{
		type:'radialGradient',
		stops:[
			[0,'blue'],
			[1,'darkblue']
		]
	},{
		type:'radialGradient',
		stops:[
			[0,'red'],
			[1,'darkred']
		]
	},'red'],*/
	title:{
		text:'统计图表测试标题',
		margin:0,
		style:{
			color:'#000'
		},
		subTitle:{
			text:'子标题测试',
			style:{
				color:'#999'
			}
		}
	},
	grid:{
		top:100,
		left:50,
		right:80,
		bottom:150,
		containLabel:0,
		background:'#eee'
	},
	legend:{
		align:'center',
		margin:40
	},
	xAxis:{
		type:'category',
		min:1.2,
		startOnTick:1,
		gridLine:{
			enabled:true,
			lineWidth:1,
			color:'#e6e6e6'
		},
		axisLine:{
			onZero:1,
			lineColor:'#000'
		},
		opposite:0,
		axisLabel:{
			margin:20
		},
		title:{
			text:'haha',
			margin:10,
			align:'end',
		},
		categories:['一','二','三','四','五','六','一','二','三','四','五','六','一','二','三','四','五','六']
	},
	yAxis:{
		type:'category',
		startOnTick:true,
		title:{
			text:'李文胜',
			align:'top',
			margin:10,
			rotation:0,
			style:{
				color:'#333',
				fontSize:12
			}
		},
		axisTick:{
			inside:true
		},
		axisLine:{
			lineColor:"#000"
		},
		gridLine:{
			enabled:0,
			lineColor:'red'
		},
	},
	plotOptions:{
		bar: {
			barWidth:null,
			borderWidth:0,
			borderColor:"#fff",
			borderRadius:'20%',
			minBarLength:5,
			maxBarWidth:500,
			groupIng:true
		}
	},

	series:[
        {
			type:'line',
			borderWidth:1,
			borderColor:'#fff',
			data:[1,2,3,4,5,6,2,3,5,2,3,2,2,3,5,2,3,2,2,3,5]
		},
		{
			type:'bar',
			data:[2,3,5,2,3,2,2,3,5,2,3,2,2,3,5,2,3,2,2,3,5]
		},
    ]
}
var chart = vchart.init(el,{
	height:600
});
chart.setOption(option);