 module.exports = {
    grid:{
        left:30,
        top:30,
        bottom:80,
        right:80,
        background:'transparent',
        containLabel:false
    },
    axis:{
        gridIndex:0,//所属网格区域
	    min:null,
	    max:null,//对于分类轴来说仍然是有意义的
	    minRange:null,
	    splitNumber:5,//分割段数
	    data:[],//分类轴用到
	    opposite:false,
	    inverse:false,//数值反转
	    title:{
	        show:true,
	        align:"start",//start middle end
	        margin:0,
	        rotation:0,
	        style:{
	            color:"#666"
	        },
	        text:"",
	    },
	    axisLine:{
	        show:true,
	        lineStyle:{
	            color:"#333",
	            width:1,
	            type:"solid"
	        }
	    },
	    axisTick:{
	        show:true,
	        interval:"auto",
	        inside:false,
	        length:5,
	        lineStyle:{
	            color:"#333",
	            width:1,
	            type:"solid",
	        }
	    },
	    axisLabel:{
	        show:true,
	        interval:'auto',
	        inside:false,
	        rotate:0,
	        margin:8,
	        textWidth:null,//强制宽度
	        formatter:null,
	        style:{
	            color:'red',
	            fontSize:12,
	            textAlign:"center",
	            textBaseLine:"bottom"
	        }
	    }
    }
}