{
	enable:true,
	layout:'horizontal',
	align:'center',
	borderColor:'#999',
	borderWidth:1,
	borderRadius:0,
	background:'transparent',
	formatter:null,
	margin:12,
	itemWidth:'auto',
	itemGap:10,
	itemPadding:5,
	selectMode:'multiple',
	inactiveColor:'#ccc',
	labelStyle:{

	}
}